atom/apm

- spec/init-spec.coffee
- src/package-converter.coffee
- templates/language/settings/language-__package-name__.cson
:rotating_light: Don't merge until atom/atom@b4246a2f07995e6c21effe7153399bee321fdf8f is released :rotating_light: 
References atom/atom#4605
> Store TextMate bundle “preferences” in /settings dir instead of /scoped-properties

- src/install.coffee
When spawning `npm` set the proxy environment variables from the config settings so that any spawned Git processes will use them.
Closes #255
> Set proxy env vars from config

- package.json
- src/apm.coffee
The 0.126.0 version has been reserved for this.
> Upgrade to Chrome40

- package.json
- src/apm-cli.coffee
- src/apm.coffee
This makes apm being able to read asar archives, merge this after https://github.com/atom/atom/pull/5382 is merged.
> Add support for asar archives

- bin/apm
From https://github.com/atom/apm/issues/282#issuecomment-100289741
> Use /usr/bin/env bash in hashbang

- package.json
- src/test.coffee
- templates/bundle/package.json
- templates/language/package.json
- templates/package/package.json
- templates/theme/package.json
Minor updates for apm 1.0 which will ship with Atom 1.0
Refs https://github.com/atom/atom/pull/7329
> Prepare apm 1.0

- Gruntfile.coffee
- coffeelint.json
- package.json
- spec/test-spec.coffee
- src/command.coffee
- src/links.coffee
- src/list.coffee
- src/login.coffee
- src/upgrade.coffee
- src/view.coffee
> Add Coffeelint Config

- package.json
This bumps npm to the latest version (2.11.2) - part of [an effort to update dependencies.](https://david-dm.org/atom/apm) Let's see if this goes green! :traffic_light:
> npm@2.13.3

- spec/link-spec.coffee
- src/link.coffee
- src/unlink.coffee
Fixes https://github.com/atom/apm/issues/391
/cc @atom/feedback
> Stringify argument to apm link / unlink

- spec/test-spec.coffee
- src/test.coffee
Refs: https://github.com/atom/atom/pull/8968
/cc: @nathansobo
> Drop --spec-directory

- src/cli.coffee
After this we can do `pidof apm` instead of doing `pidof node`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/atom/apm/468)
> Set process title in APM

- spec/uninstall-spec.coffee
- src/uninstall.coffee
hopefully this will close #395 :smile:
> should check to see if package exists before trying to uninstall it

- src/apm.coffee
Include VS2015 in the detection of Visual Studio for node-gyp etc.
> Detect VS2015 on Windows

- Gruntfile.coffee
- README.md
> Replace OS X with macOS and Linux

- spec/fixtures/install-test-module2.json
- spec/install-spec.coffee
- src/install.coffee
Remove old package if an installed package is renamed
Won't have to manually uninstall the old package if a package is renamed
Could break someones [workflow](https://xkcd.com/1172/)
#600
> Rename uninstall old module

- .npmignore
- templates/language/grammars/__package-name__.cson
- templates/language/snippets/language-__package-name__.cson
- templates/language/spec/language-__package-name__-spec.coffee.template
* Make sure that the language template's spec folder is correctly added to the npm distribution
* Link to http://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/ instead of the TextMate manual
* Use language-javascript as examples in some cases
> Update language template

- src/upgrade.coffee
fix https://github.com/atom/apm/issues/741
> Check that package directory is git repo before using git to update

- src/install.coffee
Fixes https://github.com/atom/settings-view/issues/1018
> Make rename detection case-insensitive

- package-lock.json
Coffeelint was giving us trouble on AppVeyor. This is me trying to find out why 🔍
> Lint clean

- templates/language/README.md
Fix the language package generation README template to use the package name var
regression in 6b365fd prevented language package name from populating in README
language package README populated with name
> Fix language package README name generation

- src/apm-cli.coffee
- src/ci.coffee
- src/clean.coffee
- src/config.coffee
- src/dedupe.coffee
- src/develop.coffee
- src/disable.coffee
- src/docs.coffee
- src/enable.coffee
- src/featured.coffee
- src/init.coffee
- src/install.coffee
- src/link.coffee
- src/links.coffee
- src/list.coffee
- src/login.coffee
- src/publish.coffee
- src/rebuild-module-cache.coffee
- src/rebuild.coffee
- src/search.coffee
- src/star.coffee
- src/stars.coffee
- src/test.coffee
- src/uninstall.coffee
- src/unlink.coffee
- src/unpublish.coffee
- src/unstar.coffee
- src/upgrade.coffee
- src/view.coffee
Changes the wrapping value to account for the terminal width; it will now pick the minimum of 100 (original hardcoded value) or the terminal width, if yargs can detect it (`yargs.terminalWidth()` may return `null`, so we default to 100 in this case too).
na
Cleaner display on narrow terminal windows
None
Manually, with the output of `apm --help`
na
> Better narrow terminal width support

- src/install.coffee
`apm install` can now forward the `--verbose` flag to `npm`,
forming the `npm install --verbose` command under the hood.
None.
`npm install --verbose` prints lots of useful information that can be used
to debug what happens when users try to install a package,
or when users try to install the dependencies for a package
during development.
Among other things, it tells you what Python, Visual Studio, node-gyp and Electron versions
were used during the install. It also shows detailed error messages, if there are any.
This could be extremely useful in …
> Pass --verbose flag to npm if set for apm install

- package-lock.json
- package.json
Bumps [git-utils](https://github.com/atom/git-utils) from 5.6.2 to 5.7.1.
Fixes Atom not being bootstrapped.
The CI passes now.
> fix: bump git-utils

- package-lock.json
- package.json
> Bump git-utils@5.7.2

- .github/workflows/CI.yml
> Remove node 12 from the node matrix

- package-lock.json
- package.json
> Bump first-mate
