atom/apm

spec/config-spec.coffee, spec/install-spec.coffee, src/apm-cli.coffee, src/apm.coffee, src/clean.coffee, src/config.coffee, src/dedupe.coffee, src/develop.coffee, src/docs.coffee, src/featured.coffee, src/install.coffee, src/link.coffee, src/links.coffee, src/list.coffee, src/publish.coffee, src/rebuild-module-cache.coffee, src/rebuild.coffee, src/request.coffee, src/search.coffee, src/star.coffee, src/stars.coffee, src/uninstall.coffee, src/unlink.coffee, src/unpublish.coffee, src/unstar.coffee, src/upgrade.coffee, src/view.coffee
This is essentially just a pass through to `npm config` but it makes configuring apm from the command line much easier.
For example:
```
> apm config set proxy http://9.0.2.1.0
> apm config list
; cli configs
globalconfig = "/Users/kevin/github/apm/.apmrc"
user-agent = "npm/2.1.18 node/v0.10.35 darwin x64"
userconfig = "/Users/kevin/.atom/.apmrc"
; userconfig /Users/kevin/.atom/.apmrc
proxy = "http://9.0.2.1.0/"
; globalconfig /Users/kevin/github/apm/.apmrc
cache = "/Users/kevin/.atom/.node-gyp/.atom/.apm"
; node bin location = /Users/kevin/github/apm/bin/node
; cwd = /Users/kevin/github/apm
; HOME = /Users/kevin/.atom/.node-gyp
; 'npm config ls -l' to show all defaults.
```
=> Add config command

templates/theme/styles/base.less
This *removes* the old-style selectors, which means that (without explicit
retrofitting) themes based off of this template will *not* work with
shadow DOM disabled (or on earlier versions of Atom that don't use the
shadow DOM facility).
- - - - -
[PR-only comment]
I didn't find any instructions in the repo for how to build and test `apm`, so I was unable to test this per se. However, near as I could tell from installing this file as part of a syntax theme, it works as expected.
=> Shadow-DOM-ify the template syntax theme.

spec/init-spec.coffee, src/text-mate-theme.coffee
The `TextMateTheme` class doesn't have tests, and when I tried to install the package from a folder (`npm install ~/Code/apm`) it tried to run `grunt prepublish` and complained the command couldn't be found, so I couldn't manually test it. But I think this should fix TextMate theme conversion.
=> Changing TextMate theme conversion to use current, non-deprecated selectors

src/list.coffee
This implements my enhancement suggestion in #256 – it adds a `--packages` (or `-p`) flag for only listing packages. If combined with `--themes`, it'll just list everything, which seems fine to me.
Should I add a test for this? I noticed there aren't any tests for any of the flags, so I wasn't sure. (Maybe there should be?)
Either way, let me know! :smiley: 
(Resolves #256)
=> Add --packages flag to apm list

src/apm-cli.coffee, src/develop.coffee, src/git.coffee, src/install.coffee
This PR does two things:
* Show a friendlier message when install fails because a package requires Git and Git isn't installed.  This replaces the preview giant error from npm with a little `ENOGIT` message somewhere in there.
* Put the install locations for GitHub for Windows and Git Bash on the path automatically. These aren't on the path automatically since each app includes a custom shell.
Closes https://github.com/atom/atom/issues/5193
=> Better Git error

.apmrc, .gitignore, .npmignore, Gruntfile.coffee, spec/config-spec.coffee, spec/install-spec.coffee, src/apm-cli.coffee, src/apm.coffee, src/install.coffee
This PR dynamically generates the global `.apmrc` file so that it can properly respect the `ATOM_HOME` env var which might be used for portable Atom versions.
Refs https://github.com/atom/atom/issues/2939
=> Respect ATOM_HOME in cache path

spec/publish-spec.coffee, src/publish.coffee
Checks that the `engines.atom`, `dependencies`, and `devDependencies` semver ranges are valid in the `package.json` before allowing publishing to occur.
This fixes the case where a package can be published with an invalid engines field that won't be listed as compatible and so it actually can't be installed in any Atom version.
Closes #291
=> Validate semver ranges before publishing

templates/language/LICENSE.md, templates/package/LICENSE.md, templates/theme/LICENSE.md
I noticed this while generating some packages with `apm init`. Maybe its worth making the year dynamic so its always the current year? Happy to make this change.
=> Bump year in template licenses to 2015

templates/package/lib/__package-name__-view.coffee.template
The argument object is the serialized state. Makes more sense, imo.
```coffee
constructor: (serializeState) ->
```
to
```coffee
constructor: (serializedState) ->
```
=> :art: changed constructor's argument name to `serializedState` in template for package view

bin/apm
archs is unused in this file. Remove.
Don't limit use by operating system. Set correctly for Windows and pick reasonable default for all else.
This fixes a problem on FreeBSD.
=> Don't limit by operating system type. Default to reasonable node binary

bin/apm
I've tested this on OS X, debian, and FreeBSD. I don't have the ability to test on Windows.
=> Use bash substrings instead of expr non-posix substrings for portability.

script/download-node.js
Currently, if you try to download node for unsupported architecture/operating system, you get an exception because it passes a null stream to zlib to decompress.
events.js:72
throw er; // Unhandled 'error' event
^
Error: incorrect header check
at Zlib._binding.onerror (zlib.js:296:17)
This change results in and error being printed:
download not found: http://nodejs.org/dist/v0.10.35/node-v0.10.35-freebsd-x64.tar.gz
=> Catch 404 not found case and quit stream before passing zlib empty file

templates/bundle/package.json, templates/language/package.json, templates/package/package.json, templates/theme/package.json
This adds the `keywords` field to package templates as a gentle nudge for users to add keywords when creating packages. Motivation: http://blog.atom.io/2015/03/30/keywords-on-atom-io.html + https://github.com/atom/deprecation-cop/issues/32 
cc @lee-dohm
=> Add keywords field to package templates

bin/apm
Reverts atom/apm#361
Alas, I'd hoped this would be a drop-in replacement, but it breaks installations with malformed `PATH`s.
Fixes https://github.com/atom/atom/issues/6985
=> Revert "Use /usr/bin/env bash in hashbang"

deprecated-packages.json, spec/fixtures/atom-2048.json, spec/fixtures/search.json, spec/install-spec.coffee, spec/search-spec.coffee, src/deprecated-packages.coffee, src/install.coffee, src/search.coffee
Use a list of known packages with deprecations to prevent installation of packages not compatible with Atom 1.0
Only affects the `apm search` and `apm install` commands.
Refs https://github.com/atom/atom/issues/6867
/cc @benogle
=> Don't install or show search results for deprecated packages

script/download-node.js
There is work in progress to go to node 0.12, but in the meantime this bumps apm to the latest `0.10.x` build for security fixes.
Refs atom/atom#8395
=> Upgrade to node 0.10.40

spec/clean-spec.coffee, spec/install-spec.coffee, spec/rebuild-spec.coffee, spec/stars-spec.coffee, spec/upgrade-spec.coffee, src/apm.coffee, src/command.coffee, src/dedupe.coffee, src/install.coffee, src/rebuild.coffee, src/upgrade.coffee
This pulls the `electronVersion` from Atom's `package.json` so the version doesn't need to be bumped  in this project for new versions.
@thomasjo and @mnquintana this is my take on what #409 is trying to do. I am totally onboard with moving the version configuration out of this repository and into atom/atom. I'm cautious to make upgrading to node 0.12 part of this though since I'd like to de-tangle upgrading the node version bundled with apm from upgrading Atom to using the latest Electron.
Refs #409
=> Use electron version from Atom's package.json

package.json
`yargs@3.23.0` eliminates the dependency on spawn-sync, to prevent regressions like we had last week yargs now has:
windows testing via AppVeyor: https://ci.appveyor.com/project/bcoe/yargs
_and_
OSX testing via Travis: https://travis-ci.org/bcoe/yargs
=> upgrades yargs dependency to ^3.23.0

spec/fixtures/package-with-native-deps/package.json, spec/rebuild-spec.coffee, src/command.coffee, src/install.coffee, src/rebuild.coffee
We now run `apm rebuild` from within Atom to rebuild incompatible packages. Unfortunately, it's breaking unless you launched Atom from the command line with a `PATH` that happens to contain a valid `node` executable. This changes the `rebuild` command to use the bundled `node`, just like we do for `apm install`.
Refs https://github.com/atom/atom/issues/8837
=> Use bundled node in `apm rebuild`

.travis.yml, bin/apm, bin/apm.cmd, package.json, script/download-node.js
I reckon it's about time to head for greener pastures — Node v4. Ensuring apm runs on v4 should help @jlord with getting Atom to run on ARM machines. In addition Node v4 has all the performance improvements, ES6 support, bug fixes, etc. that were added to io.js.
I experimented with bumping npm to v3 (3.3.6) but that proved less trivial due to the removal(?) of `peerDependencies`, so that will require more changes, and testing.
Note that I also bumped npm to v2.14.7 (latest stable v2 version as of writing this); I can easily yank that change if someone wants to keep the changeset here as minimal as possible.
/cc @atom/feedback 
---
Supersedes #430
Refs https://github.com/atom/atom/issues/7822
=> Upgrade to Node v4.x

templates/theme/styles/base.less
:art: Having two seperate .entity sections leads to confusion. 
This way you don't get people adding subsections to the first .entity entry, which then get overridden by the second .entity entry.
=> Merge two seperate .entity sections into one.

src/dedupe.coffee, src/install.coffee, src/request.coffee
as issue #398 requested I've made it so that npm looks for the environment variables HTTPS_PROXY and HTTP_PROXY to use if the proxy is not set within the config file. 
when setting my HTTPS_PROXY variable to http://proxy.com:8080 it is picked up by apm and added to the request as show in below screenshot:
=> make apm look for proxy env variables if not already in the config

spec/disable-spec.coffee, spec/enable-spec.coffee, spec/fixtures/test-module-three/package.json, spec/fixtures/test-module-two/package.json, src/apm-cli.coffee, src/disable.coffee, src/enable.coffee
Addresses https://github.com/atom/apm/issues/358 and https://github.com/atom/atom/issues/5987.
There's some code duplication but that seems to be apm's style: commands and tests are mostly self-sufficient.  I wanted to make the new commands resemble the existing ones.
=> Add enable and disable commands

README.md
Changed the README.md file to suggest using the apm command line tool to set the proxy configuration item rather than manually editing the .apmrc file.
Manually editing the ~/.atom/.apmrc file doesn't work if you run Atom on Windows by downloading the zip, extracting it and running it from a directory. In this case, the ~/.atom/.apmrc file is overwritten every time the apm command is executed. However, running the command line persists the changes successfully.
=> Update documentation on proxy usage

src/auth.coffee
Otherwise auth failures get confusing: we’d keep updating the token
stored in the keychain when the real problem was that `ATOM_ACCESS_TOKEN`
was out of date. See #505.
=> Check the keychain for the token before falling back to ATOM_ACCESS_TOKEN.

package.json
With a clean checkout I was getting the error:
Running "coffee:glob_to_multiple" (coffee) task
>> 41 files created.
Warning: Task "coffeelint" not found. Use --force to continue.
Aborted due to warnings.
npm WARN grunt-coffeelint@0.0.13 requires a peer of coffeelint@^1 but none was installed.
Upgrading the grunt-coffeelint package from 0.0.13 to 0.0.15 made this go away.
=> Upgrade grunt-coffeelint to 0.0.15 

spec/command-spec.coffee, spec/test-spec.coffee, src/command.coffee
If a process spawned with `Command::spawn` exited with an error, we were finding that both `on("error", ...)` and `on("close", ...)` were being called, resulting in the callback to `spawn` being called more than once.
Signed-off-by: Katrina Uychaco @kuychaco
=> Ensure callback to Command::spawn is only called once

spec/install-spec.coffee, src/command.coffee, src/develop.coffee, src/install.coffee
Since Atom doesn't know the official name of packages when installing from Git URLs, we need a mechanism for passing that information from apm back to Atom so `settings-view` can activate the newly installed package.
=> Output package installation information when using --json

src/uninstall.coffee
I do not understand how it is an error unless both a dev package exists **and** a package exists.
Uninstall hard **should succeed** if the packages do not exist afterwards.
=> Do not throw errors if packages do not exist on apm uninstall --hard

spec/unpublish-spec.coffee, src/unpublish.coffee
Let's avoid another https://discuss.atom.io/t/apm-publish-help/28414
This PR includes two changes:
* If you `apm unpublish my-package` (without a version), apm attempts to make it *explicitly clear* what's about to happen.
* If you simply presses enter at the confirmation prompt, the default behavior is to cancel the unpublish; only "yes" or "y" will actually perform the destructive operation. Use `--force` if you *really know* you want to unpublish.
/cc @lee-dohm
=> Make accidental unpublishes harder

package.json, src/cli.coffee
Calling `process.exit()` keeps the stdout and stderr from fully flushing. The `exit` module handles this, but in more recent Nodes, we can simply set `process.exitCode` and let Node exit when it's done with the event loop.
=> Fix output truncation when exiting

script/download-node.js
This should fix https://github.com/atom/apm/issues/568.
I noticed for the first time an error message that said:
```
download not found: http://nodejs.org/dist/v4.4.5/node-v4.4.5-linux-arm.tar.gz
```
I checked [the Node distribution page](https://nodejs.org/en/download/current/) and found that the URL for ARM machines includes the ARM CPU version.
=> Download the correct Node binary for ARM machines

package.json
The primary goal of this PR was to silence the graceful-fs spam when building Atom, etc. Turns out there are other deprecations as well that should be resolved. In particular the fact that [wrench](https://www.npmjs.com/package/wrench) has been deprecated with a recommendation to replace it with [fs-extra](https://www.npmjs.com/package/fs-extra).
- ~~Replace wrench with fs-extra (or something else).~~ Expands the scope of this PR too much. Better to do that work in a separate PR.
=> Upgrade deprecated packages

appveyor.yml, bin/npm, bin/npm.cmd, package.json, script/bundled-node-version.js, script/download-node.js, script/postinstall.cmd
This should unblock using AppVeyor on atom/atom#12170.
The main issue with the previous scripts was that we were building the URL for downloading Node x86 for Windows in a wrong way, which was preventing it from being downloaded. As part of fixing that, we have also restructured the scripts a little bit to make them more similar to their Mac/Linux counterparts.
Please, note that we have disabled running tests because some of them appear to be written in a platform-specific way. I think fixing them can be deferred to another pull-request, so that we can start using the new version of apm on Atom right away. /cc: @damieng 
/cc: @nathansobo @atom/core
=> Fix Windows build

package.json
This should fix a problem with running `npm install` when there are extraneous dependencies within the `node_modules` folder.
=> Update npm to v3.10.5

src/apm.coffee
This regressed in #562, causing every `apm` command that delegates to `npm` to show something like the following:
With this pull-request we disable progress report by default in `~/.atom/.apm/.apmrc`, so that running `npm` commands doesn't show the native progress-bar.
/cc: @BinaryMuse @kuychaco @nathansobo @atom/core
=> Disable progress when running npm

src/dedupe.coffee, src/install.coffee, src/rebuild.coffee
This pull-request fixes a problem when installing dependencies via `apm` that prevents the runtime from being recognized, causing packages such as nodegit to fail the build. In particular, we are adding the `--runtime=electron` flag to every `npm` command that interfaces with modules installation and their subsequent compilation. 
Please, note that this is the approach that [electron-rebuild uses too](https://github.com/electron/electron-rebuild/blob/27158b165715731836425369c5c5e680420c7cd9/src/main.js#L122-L126).
While in the process of adding such flag, we spotted a couple of places in the `dedupe` command where the target architecture of native modules was being hardcoded; this was probably not an issue, but it feels reasonable to use `config.getElectronArch()` as we do elsewhere. …
=> Fix missing and hardcoded flags

src/init.coffee, templates/language/LICENSE.md, templates/package-coffeescript/LICENSE.md, templates/package-javascript/LICENSE.md, templates/theme/LICENSE.md
We need to update year in template every year. It should be automated :smiley_cat:
=> Bump year in template automatically

package.json, spec/init-spec.coffee, src/text-mate-theme.coffee, templates/theme/styles/base.less
We are in the process of removing the shadow DOM boundary from `atom-text-editor` elements. This pull request upgrades existing selectors so that they:
* Stop using `:host`.
* Stop using `atom-text-editor::shadow`.
* Prepend syntax class names with `syntax--`.
=> Stop using shadow DOM selectors

spec/upgrade-spec.coffee, src/apm.coffee, src/config.coffee, src/dedupe.coffee, src/install.coffee, src/rebuild.coffee
This will make sure that overriding the `$HOME`/`$USERPROFILE` environment variable won't prevent tools like `cargo` or `rustc` from working appropriately on Windows. By default, we will honor the existing `$RUSTUP_HOME` if set, or set it to `$HOME/.multirust` (rustup's default) otherwise.
It's worth noting that an [RFC](https://github.com/rust-lang/rfcs/pull/1615) is being discussed to change the default rustup home directory to `~/.rustup`, so we'll probably need to change this default in the future in case that gets updated. I imagine that it will not happen without a reasonable notice, so we will have time to update such location. In addition, by the time the RFC gets approved and implemented, I am hoping we will have a better situation with respect to overriding the `$HOME` and …
=> Set `$RUSTUP_HOME` when running `npm` and `node-gyp`

spec/list-spec.coffee, src/list.coffee
=> ensure (empty) isn't printed when no git packages

src/command.coffee
I have **winreg** on **package.json** (Atom) linked to **github:jsolisu/node-winreg**, when i use: _script\build_ or _script\bootstrap_ APM fails with _"Installing modoles failed..."_
The problem is because PATH is undefined. I revert changes from 1.15.0 using 1.14.1 version of _command.coffee_
[npm-debug.log.txt](https://github.com/atom/apm/files/587501/npm-debug.log.txt)
=> Fix "Installing modules failed" on Atom

.travis.yml, script/postinstall.js
Use `child_process.spawn` instead of  `child_process.exec`.
Fixes #636
=> Fix build on Node 7

src/apm.coffee
Both URLs are still available and serve the same assets, but this one uses the new name for Electron, not the old one Atom Shell.
=> Update Electron headers URL

src/upgrade.coffee
Using `async.map` to get the latest versions for all packages probably fires hundreds of simultaneous requests to the webserver (depending on how many packages are installed). Replacing this with `async.mapLimit` ensures that only (in this case) 10 connections are made at once.
No alternates came in mind since async was already the right tool for the job.
Preventing the client from having to open too many simultaneous connections opened which caused real problems for some users which resulting in updates not working at all.
Theoretically it could result in a slower update process since we're only requesting information for a maximum of 10 packages at once. Seeing the current problem of people not be able to update at all this might be a drawback they'll likely accept.
Fixes #641
=> Replacing async.map with async.mapLimit to adress #641

src/text-mate-theme.coffee, templates/theme/styles/base.less
If we get a textmate theme (e.g. https://raw.githubusercontent.com/JetBrains/colorSchemeTool/master/tmThemes/Monokai.tmTheme).
And try to convert it to an atom theme using apm as shown in the docs:
http://flight-manual.atom.io/hacking-atom/sections/converting-from-textmate/
The resulting theme (if we chose it as the current syntax theme on settings) will display a deprecation warning about two class selectors:
> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
> 
> atom-text-editor …
=> Remove obsolete .marker and .search-results CSS rules

src/apm.coffee
As illustrated in https://github.com/atom/atom/pull/13916, we don't need to produce an asar bundle in Atom anymore. This pull request changes `apm` to use the non-asar locations when determining the resource paths.
=> Stop using asar archives

bin/apm
Correctly launch the Windows native version of APM from the Windows Subsystem for Linux (WSL)
Fixes https://github.com/atom/atom/issues/14258 along with https://github.com/atom/atom/pull/14287 for Atom
=>  Run APM from Windows Subsystem for Linux

package.json
Updating the bundled version of npm to avoid npm/npm#13256, which was breaking the installation of packages with native dependencies.
=> npm version bump

spec/list-spec.coffee, src/list.coffee
apm doesn't show `(disabled)` anymore after disabled packages.  This PR fixes that.
It looks like this functionality has been broken for a while.
Found by @michaelsanford in https://github.com/atom/apm/issues/616
=> fix apm list to show packages as disabled again

package.json
We're matching the same version that the bundled npm depends on. This will help us ensure that regardless of how npm organizes the directories, we will know how to access the node-gyp binary. The risk is that someone will update npm without updating node-gyp.
=> Depend on node-gyp explicitly

package.json, src/apm.coffee
Reverts atom/apm#693, since we turned .asar archives back on as part of https://github.com/atom/atom/pull/14682.
@nathansobo: I believe this will fix the `Could not determine Electron version` error we were observing when running `apm install`.
/cc: @iolsen
=> Revert "Stop using asar archives"

spec/list-spec.coffee, src/list.coffee, src/package-converter.coffee
My change is in response to atom/first-mate#51 – an issue which requested that Atom Package Manager give more information, such as file names and line numbers, in regards to errors when converting TextMate Bundle files to an Atom digestible format. 
I decided to apply the fix in apm instead of first-mate since the information required to locate the source of the error is not made available to first-mate. Additionally, it appears to be near impossible (or at least efficient) to ascertain an exact location of an error, so I elected to output the malformed piece of text instead, which should hopefully give enough information to the user to debug their program.
Due to a mistake on my part, instead of opening a new pull request for this change, I accidentally merged it into this pull request. …
=> Textmate conversion error reporting & apm list --enabled

src/auth.coffee
This fixes two issues related to `keytar`'s recent switch to a Promise-based API (see atom/node-keytar#63). 
* If `keytar.findPassword`'s promise was rejected, there was an uncaught promise rejection exception, instead of falling back to `process.env.ATOM_ACCESS_TOKEN`. That's fixed.
* If `keytar` failed to load, the stub for `findPassword` would return `undefined` instead of a promise. That's fixed.
* The `keytar` stub module had a `replacePassword` method, when it should in fact be `setPassword`. That's fixed.
None.
Nuclide publishes from CircleCI, which is where this issue was found. See `./scripts/oss-publish.sh` in https://circleci.com/gh/facebook/nuclide/1537
```
(node:18872) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Address element …
```
=> Always fall back to ATOM_ACCESS_TOKEN when there is no token

bin/apm, bin/npm, spec/fixtures/fake-python-1.sh, spec/fixtures/fake-python-2.sh, spec/install-spec.coffee
This captures the various ways that node-gyp can find its Python executable within the entrypoint scripts and forwards them to the Python interceptor script as `ATOM_APM_ORIGINAL_PYTHON`. python-interceptor then execs `ATOM_APM_ORIGINAL_PYTHON` instead of a hardcoded "python".
Furthermore, this deals with some odd edge cases related to `npm` being _case-insensitive_ when it reads `npm_config_*` variables from its environment. If a user had something like `NPM_CONFIG_PYTHON` or `npm_CONFIG_node_GYP` set in their environment the results would technically be …
=> Respect a user's PYTHON or npm_config_python settings

spec/packages-spec.coffee, src/packages.coffee, src/publish.coffee
I often have repositories where the "official" remote isn't `origin`. Most of the time the desired remote would be named `upstream` or similar.
To publish a new version one needs to make sure that `origin` points to the upstream repo where the package should be publish. This behavior can sometimes be very anoying.
This PR will determine the remote from the `package.json` file and fall back to `origin`.
Fixes #343
=> Determine remote from package.json

spec/clean-spec.coffee, src/clean.coffee
Scoped packages put dependencies in a sub-folder. Therefore if a scoped package is encountered, recursively iterate through the directory to correctly resolve the scoped name.
Keeping track of the scoped packages, but that would be very memory intensive.
It no longer infinitely loops when a scoped packages is installed in `node_modules`
Maybe a little bit slower, but I don't think that is a too big of an issue.
Fixes #702
=> :bug: Fix cleaning of scoped packages

bin/apm
Fix this error, encountered when installing a package with native dependencies from an installed `apm` script:
```
Error: Can't find Python executable "/usr/local/bin/python-interceptor.sh", you can set the PYTHON env variable.
```
/cc @maxbrunsfeld
=> Use $binDir instead of $scriptDir to find python interceptor script

spec/apm-cli-spec.coffee, src/apm-cli.coffee
Using `spawn` in `getPythonVersion`, similar to @arabelle's approach. See: https://github.com/arabelle/apm/blob/59f70d50571090fe205bf6b03c03f0c86398f5f4/src/apm-cli.coffee#L132-L143
I did not want to spawn a new process and parse it's output since I have access to Atom's  `package.json`
Closes #382
There is [a workaround](https://github.com/virtuoushub/apm/blob/2322ed592e6e75c83200f09a2c62cd4e4d1e4df1/src/apm-cli.coffee#L138-L140) due to [an issue](https://github.com/atom/atom/issues/6604) on macOS I ran into while testing. Ideally, the workaround that checks with [`getResourcePath`](https://github.com/atom/apm/blob/a6285bc4e90e442906bc86542f885f79e2dea15e/src/apm.coffee#L23-L51) is not used.
#453, #473, and [atom/atom#6604](https://github.com/atom/atom/issues/6604)
/cc @jebschiefer and …
=> Add Atom version to the printed version information

spec/list-spec.coffee, src/list.coffee
As requested in https://github.com/atom/apm/pull/400#issuecomment-253913575
This is based on top of #617 so that PR should be merged first.
=> add --enabled and --disabled flags to `apm list`

README.md
Add a note to the README's "Using" section about working with 2fa-enabled accounts.
Fixes #768.
=> Working with 2fa

package-lock.json, package.json
This change updates `apm` to use `npm` 6.2.0 to benefit from some [major dependency restructuring and flattening](https://github.com/nodejs/node/pull/21592) that shaved about **60** characters off of `npm`'s directory tree paths, specifically to aid with installing Node.js on Windows.
Since we've been fighting with "path too long" errors with Squirrel for a long time, this new version of `npm` is a welcome relief and a path forward to finally deliver side-by-side Atom release channel installations on Windows.
I also tried running `npm dedupe` in Atom's `apm` folder in various different ways and it either broke `apm`, broke Atom's app packaging, or had no real effect.  Updating to `npm` 6.2.0 is the only thing that brought results.
I also tried updating to `npm` 6.3.0 but ran into some …
=> Upgrade npm to 6.2.0 to fix Windows long file path issues

src/disable.coffee
Doesn't unpack array of package names when calling [`_.union`](https://underscorejs.org/#union), so it works properly. The original version only worked because of a bug in underscore.js, which was patched some time between version 1.6.0 and 1.8.3 (of _.js). They have now explicitly prevented non-arrays from appearing in the output of a union. I.e., `_.union([1, 2], 3, [4]) === [1, 2, 4]` (and that 3 was the disabled package...)
Actually disable packages
I don't know why the spread was there initially. I compiled and tested though, and disabling worked fine.
Fix #801 
Fix atom/atom#17741
=> Don't unpack array

spec/link-spec.coffee, src/link.coffee
Add a `--name` option to `apm link`
```
apm link [<package_path>] [--name <package_name>]
```
We could also add the `-n` short option
- Set the name of a linked package easily
- Being able to have two versions of the same package (Most likely one of them disabled based on context)
- Overriding a core package with a local package
Right now the way to do this is to change the `name` field in `package.json`, then link the package, then change the `name` field back.
none?
none
=> add `apm link --name` option

package-lock.json, spec/install-spec.coffee, src/install.coffee
This change adds support for npm's `file:` syntax for `packageDependencies` in Atom's `package.json` file.  When a package dependency uses such a string with a relative path, we use a special code path that knows to pass along that path to npm so that the package can be installed from the local folder into `node_modules`.
I don't know of any other way to accomplish this with `apm` currently, but I'd be happy to learn of alternatives!
This allows Atom to easily use core packages which live inside a subfolder of Atom's own repository instead of having to ship core packages to apm and then reference them with version numbers in `packageDependencies`.
Currently there's no way to determine that a package from a local path and its "installed" copy under `node_modules` are the same and don't …
=> Add support for repo-local packageDependencies in Atom's package.json

package-lock.json, package.json, script/postinstall.sh
When the system's host node has the same native module version as the downloaded one, don't rebuild native modules in the postinstall script. This should keep us from building libgit2 and oniguruma twice on every install. ✌️ 
Also: optionally disable automatic npm deduplication during postinstall by setting a `NO_APM_DEDUPE` environment variable. I doubt we'll be able to get away with this in our real builds because of the Windows pathlength thing, but it'll help me narrow down the cause of build failures in atom/atom#17803.
=> Prevent unnecessary native module rebuilding

spec/clean-spec.coffee, src/clean.coffee
npm has added a first-class command, [prune](https://docs.npmjs.com/cli/prune), to do precisely what `apm clean` was doing manually. Let's just use theirs, it should be a lot less prone to infinite loops :smile:
Fixes #746.
=> Use "npm prune" to implement "apm clean"

spec/docs-spec.coffee, spec/featured-spec.coffee, spec/publish-spec.coffee, spec/rebuild-spec.coffee, spec/search-spec.coffee, spec/unpublish-spec.coffee, spec/upgrade-spec.coffee, spec/view-spec.coffee
A bunch of apm's specs create an express.js server to mock the npm and atom.io APIs. However, both `server.listen()` and `server.close()` are asynchronous, and if one spec's test is not closed before the next starts, the setup for the next fails with an `EADDRINUSE` error. It tends not to happen because of accidental ordering of asynchronous ticks... but if you anger the async gods, it can easily cause spurious failures.
I'm preventing this from happening by using a callback and a `waitsFor` guard in each `beforeEach` and `afterEach` clause.
=> Improve spec stability

script/postinstall.sh
Reverts part of #808.
Native modules built on Windows with apm 2.1.1 are failing to initialize properly with a curious error:
```
A dynamic link library (DLL) initialization routine failed.
\\?\C:\projects\github\node_modules\keytar\build\Release\keytar.node
```
The only relevant change in apm 2.1.0 is #808, so it must be necessary to rebuild native modules on Windows even if the module version is unchanged... ? I have no idea why this would make a difference.
=> Restore npm rebuild call

spec/install-spec.coffee, src/install.coffee
This change optimizes the installation of repo-local `packageDependencies` by ensuring that they don't get installed a second time when running `apm install`.  Since `npm` adds the same repo-local package path to the `dependencies` section after it has been installed via the `packageDependencies` section, `npm` will then install it during the initial `npm install` phase that `apm` runs.
`apm` had been running a second install of all repo-local packages, ignoring the fact that `npm` had already installed them.  This has contributed to gradually increasing build times in the Atom repo.
This changes makes `apm`'s installation of `packageDependendencies` aware of duplicate repo-local package entries in the `dependencies` section so that they don't get installed a second time unnecessarily. …
=> Avoid duplicate installs of repo-local bundled packages in package.json

script/postinstall.js
We need to make sure that the postinstall script is executable for installation not to fail. However, previously, when publishing apm on a Windows machine, `postinstall.sh` would lose execute permissions. This fixes that by chmod'ing the file right before running it to ensure the correct permissions.
None.
apm can now be published on Windows without downstream installation failures.
None.
Well, I suppose we'll find out if this works when I publish a new release.
=> Ensure postinstall script is executable

spec/install-spec.coffee
One of the tests used an async `fs.cp` to copy files from one place to another, but didn't wait for the copy to finish before proceeding with the test. _Usually_, the copy finished fast enough, but sometimes not all of the files would get copied over in time, leading to spurious "module not found" errors from node-gyp. The fix is simple - change the async copy to a sync one (and set permissions as required).
None.
Less flaky tests.
None.
I've committed this change on #840 and #839, and I haven't seen the test fail anymore.
None.
=> Fix test that was using async copy without waiting for it to finish

.npmignore, script/bundled-node-version.js, script/download-node.js, script/postinstall.js
x86 builds on Azure Devops were using an x64 version of Node to rebuild dependencies. An x86 version of Node was then used to require those dependencies, leading to a fatal exception.
Lack of Windows developer support. In addition to [no tests on Windows](#839), the development workflow was set up such that it assumed a Unix environment. apm downloads a compatible version of Node for local use, which is ignored when publishing. However, the `npmignore` file only considered the possibility of a `bin/node` file, not the possibility of a `bin/node.exe` file. …
=> Introduce better Node detection

script/postinstall.js
Just chmod all of them to be safe. We've been running into permission errors with ./bin/npm.
=> chmod all the scripts in bin

script/postinstall.js
This gives execute permission for everyone even if Atom is installed as root:
https://github.com/atom/atom/issues/19367
=> Mark all scripts as 0o755

spec/install-spec.coffee, src/ci.coffee, src/command.coffee, src/dedupe.coffee, src/install.coffee, src/rebuild.coffee
Currently, any time we have a command that does something related to `npm install`, we ensure that the Electron header versions are correctly installed by spawning a process to run `node-gyp install` with the correct Electron version, header URL, etc. It turns out that `node-gyp` will actually [do this for us](https://github.com/nodejs/node-gyp/blob/721eb691cf15556cc2700eda0558d5bad5f84232/lib/configure.js#L71) automatically as long as you supply the correct arguments to the relevant `npm` commands. Yay!
None.
There's pretty much no node-gyp code in the …
=> Remove unnecessary node-gyp header install logic

src/command.coffee
_Something_ in npm doesn't seem to like the hyphen in `dist-url`, and the argument doesn't get passed down correctly to node-gyp. This is evidenced by the fact that the corresponding environment variable for this flag is `npm_config_disturl`, **not** `npm_config_dist_url`, and that node-gyp [also accepts `--disturl`](https://github.com/nodejs/node-gyp/blob/81f3a923386acfedf22d5b8c34372ec41e3b3096/lib/process-release.js#L18).
Therefore, change the flag to `--disturl` so that things work correctly and we don't try to download iojs.
* Specify all the build …
=> Use disturl, not dist-url

src/publish.coffee
Publishing doc tweaks:
- Adds a `v` to the publish message; from `Prepare 1.12.0 release` to `Prepare v1.12.0 release`
- Expands the description of the `--tag` flag to specify `v` is required.
Could remove the `Must be of the form vx.y.z` message from the inline flag description, as it's also stated in the block of text, but I feel it's easier not to miss if it's also there.
Make required steps clearer.
none
Tested `npm version minor -m "Prepare v%s release"` on a dummy package; the git commit message was `Prepare v0.38.0 release` as expected.
The doc …
=> Improved publish version message

spec/link-spec.coffee, src/unlink.coffee
Makes a mistake in unlinking much easier to detect. Previously, if the passed file was not a valid symlink it would fail silently (and log it as a sucess). With this change, we rely more on the fact that `unlinkSync` throws an error if it doesn't work. Note this is not a spec / behaviour change; the method was able to throw an error already.
Considered catching non-existence in an else block for `if fs.isSymbolicLinkSync(pathToUnlink)`, but decided it was cleaner and more consistent to rely on the `fs.unlinkSync` errors. Note it still only deletes …
=> Better unlinking behaviour

spec/uninstall-spec.coffee, src/uninstall.coffee
Resolves `.` to the name of the current directory when running `apm uninstall .`. It then continues as if the resolved value was the one passed in the first place.
Exactly what to resolve `.` to is tricky. IMO, resolving to the exact current directory is reasonable, but then it doesn't respect the `--dev` flags and such. It also turns the command into a pseudo `rm -rf` instruction, which could be dangerous (it already acts like this on the `packages` directory, and is very annoying). As this PR is currently, any mistakes are isolated to the `packages` and …
=> Resolve `.` as folder name when uninstalling

spec/uninstall-spec.coffee, src/uninstall.coffee
When running `apm uninstall foo`, we construct a path like `~/.atom/packages/foo` to determine which package folder to remove. We added a special case for `apm uninstall .` in #854, but this still leaves us vulnerable to things like `apm uninstall ..`, which would delete the entire `.atom` folder. To protect against this, this PR updates `apm` to only delete the resolved folder if it contains a `package.json` file.
/cc @Aerijo
=> Only delete folders containing a package.json on uninstall

src/command.coffee
Adds the build environment as environment variables. This is more robust than flags, as the process environment will normally be passed along, even if the installation script does not handle and pass the flags.
For example, see [node-pty](https://github.com/microsoft/node-pty/blob/master/scripts/install.js). It defines a custom install script, which does not pass any outer flags to node-gyp. It does use the default `process.env` however.
Could potentially remove the flags now, but I wanted to keep the impact minimal.
If the build works, it's probably for …
=> Add build env values

spec/list-spec.coffee, src/list.coffee
`apm list` is used to list the currently used packages. There's multiple flags to it, but this PR only touches on the default behaviour of `apm list`, and `apm list --bare`.
`apm list` will print out a nicely formatted tree structure, listing, for each type of package, the package name and its version, with the format `package-name@package-version`. And with a newline of separation between each package type tier.
`apm list --bare`, will work similarly, but it will only print out the package with the previous format, and will not have any tree structure, nor will it include what type of package the list ones are.
This PR adds a new flag, always true by default, `--versions`, that when used as `--no-versions` will not display the version information on both of those commands, leaving the …
=> Add flag to list to not show packages' versions

package-lock.json, package.json, spec/install-spec.coffee
This uses npm's built-in node-gyp which is used in the tests. The tests assume that node-gyp should exist in node_modules, but this is an assumption about the test environment which may not be true. npm does not hoist `node-gyp` which is a dependency of the `npm` to the top-level `node-modules` in the newer versions. It adds `node-gyp` to devDependencies just for `install-spec` test.
https://github.com/atom/apm/blob/475d35f92b0e257bb0c3fdbdb8e302ee8fb0d2bb/spec/install-spec.coffee#L536-L541
The tests now pass correctly. This is tested on Atom too: https://github.com/atom-ide-community/atom/pull/103
none
N/A
Closes #10
=> use node-gyp correctly in the tests

package-lock.json, package.json, spec/apm-cli-spec.coffee, src/apm.coffee
- This fixes getResourcePath so it finds the installation location on Windows. It results in the correct behavior of several `apm` commands (such as apm --version) when apm isn't bundled with Atom.
- It also optimizes getResourcePath by storing a cache of the asarPath. This means asarPath is only calculated once.
Allows more `apm` commands (examples: `apm --version`, `apm install [package-name]`)
to work on Windows, even outside of a full Atom installation. For example:
- Allows `apm --version` to work during the Atom bootstrap script.
- Allows testing apm from inside its own git repository on Windows.
None.
The tests are included: https://github.com/atom/apm/pull/906/files#diff-845586f656569b8df7748376c8e75465R47
Manual tests:
Manually ran `apm --version` in the `apm` Git repo. Output is …
=> Fix getResourcePath so more apm commands work on Windows

script/postinstall.cmd
Linux and macOS have respected a `NO_APM_DEDUPE` env var for a long time. When this env var is set, the `postinstall` script skips running `npm dedupe`.
This PR adds a few lines to the Windows-specific `script\postinstall.cmd` file to do the same thing on Windows.
- Make deduping off by default (actually, I think I prefer this over "deduping is on by default", now that I'm thinking about it.)
- Remove deduping entirely from the `postinstall` script. (This would also be a good option).
This enables installing `apm` with `npm ci` in the Atom repository. …
=>  Respect the "NO_APM_DEDUPE" env var on Windows (for the postinstall script)

src/apm.coffee, src/ci.coffee, src/command.coffee, src/dedupe.coffee, src/install.coffee, src/rebuild.coffee
Main change:
- Detect Visual Studio 2017 and 2019
Related changes:
- Stop detecting unsupported versions, which node-gyp refuses to use (Visual Studio 2010 - 2013)
- Don't set the `--msvs_version` node-gyp flag, which sets a specific version of Visual Studio that node-gyp must find, or else it will error out.
- Our detection for actually-working Visual Studio installs is substantially worse than node-gyp's. We should let them detect and use whatever usable version of Visual Studio they can find.
<details><summary>Explanation (click to expand):</summary> …
=> Better Support for Visual Studio 2017 and 2019

.gitattributes
By @DeeDeeG 
- Use the [`.gitattributes`](https://www.git-scm.com/docs/gitattributes#_eol) file to ensure:
-  `.cmd` files are checked into/checked out of the git object store with Windows-friendly `CRLF` line endings.
- bash scripts use Unix-friendly `LF` line endings.
See: https://en.wikipedia.org/wiki/Newline#Issues_with_different_newline_formats
None.
With this change, users should get working scripts as part of their `apm` install, regardless of what platform the module was published from.
(Wrong line endings can cause scripts not to run. It appears that without this PR, files may be checked out locally with wrong line endings, and subsequently published to the npm package registry with wrong line endings.)
(This PR expected to prevent platform-specific files from being published to …
=> .gitattributes: Set platform-specific line-endings

script/postinstall.cmd, script/postinstall.sh
This PR removes a couple of lines in `script/postinstall.cmd` and `script/postinstall.sh` that performed an `npm dedupe` toward the end of the `postinstall` script when installing `apm` itself.
- Could keep automatic deduping in, but make it off by default/enabled with an env var
- (I wonder if anyone would use the env var and enable deduping? Is that any easier than just running `npm dedupe` manually?)
- Example implementation: [`381120d..a93c88a`](https://github.com/DeeDeeG/apm/compare/381120d1616d9896277a49f04ead807d8958b039..a93c88ab28e2c38f5c75c5240ac …
=> script: Remove automatic deduping from postinstall

templates/language/spec/language-__package-name__-spec.coffee.template
The `atom.syntax` global doesn't exist. This PR renames it to `atom.grammars` to make the specs for a template repo pass.
=> Fix textmate language template spec
